### ISSUE TITLE
Check for Updates results in "PKIX path building fails"

### ISSUE THREAD

**Issue by KES48** [PhilippSalvisberg/sqldev-update#1]
Dear sirs,

I did attach two Images showing what happens if I try to downlopad updates in sqldeveloper 
Version used: 19.4.0.354 
Build: 354.1759

It would be great, if somebody could tell me how to get around this Problem.

Kind regards, Klaus 

![22-01-_2020_09-33-23](https://user-images.githubusercontent.com/28626365/72879130-8fc99780-3cfc-11ea-995e-19df77128871.jpg)
![22-01-_2020_09-32-03](https://user-images.githubusercontent.com/28626365/72879133-8fc99780-3cfc-11ea-9d1e-55b51ac004ed.jpg)

**Comment by PhilippSalvisberg** [comment]
I guess you use a SQL Developer version without a bundled JDK, right? - Please use a JDK 1.8u101 or higher. Otherwise the letsencrypt certificate is not found in the default keystore.

You can check the Java version in the About dialog of SQL Developer (Help -> About -> Version).

**Comment by KES48** [comment]
Hello Philipp,

thank you very much for your quick reply!

Well ... I guess I have a complete SQL Developer version with bundeled JDK, at least that is what I did download:

configuration\	<DIR>	13.01.2020 12:25	----
dataminer\	<DIR>	13.01.2020 12:25	----
dropins\	<DIR>	13.01.2020 12:25	----
dvt\	<DIR>	13.01.2020 12:25	----
equinox\	<DIR>	13.01.2020 12:25	----
external\	<DIR>	13.01.2020 12:25	----
ide\	<DIR>	13.01.2020 12:25	----
javavm\	<DIR>	13.01.2020 12:25	----
jdbc\	<DIR>	13.01.2020 12:25	----
jdev\	<DIR>	13.01.2020 12:25	----
jdk\	<DIR>	13.01.2020 12:25	----
jlib\	<DIR>	13.01.2020 12:25	----
jviews\	<DIR>	13.01.2020 12:25	----
module\	<DIR>	13.01.2020 12:25	----
modules\	<DIR>	13.01.2020 12:25	----
netbeans\	<DIR>	13.01.2020 12:25	----
orakafka\	<DIR>	13.01.2020 12:25	----
rdbms\	<DIR>	13.01.2020 12:25	----
sleepycat\	<DIR>	13.01.2020 12:25	----
sqldeveloper\	<DIR>	13.01.2020 12:25	----
sqlj\	<DIR>	13.01.2020 12:26	----
svnkit\	<DIR>	13.01.2020 12:26	----
sqldeveloper.exe	90.736	20.12.2019 18:11	-a--
icon.png	1.404	20.12.2019 17:59	-a--
sqldeveloper.sh	71	20.12.2019 17:59	-a--

And the version info shows me this:

Info
----

Oracle SQL Developer 19.4.0.354
 Version 19.4.0.354
Build 354.1759

IDE Version: 13.0.0.1.42.190403.1502
Product ID: oracle.sqldeveloper
Product Version: 19.3.0.354.1759

Version
-------

Komponente	Version
==========	=======
Oracle-IDE	19.4.0.354.1759
Java(TM)-Plattform	1.8.0_221

**Comment by PhilippSalvisberg** [comment]
Okay, I checked it on a client's Windows PC. I was able to install it without any problems. So it's not a general issue..

Since you can select the extensions to install, the problem is not directly related to the update site. Downloading the referenced zip files (all of them on GitHub) fail. I have no idea why. Some companies restrict application access to the Internet to avoid downloading and installing potential malware. In such cases, you cannot use an update site. The workaround is to manually download and install the appropriate extensions from a file.

**Comment by KES48** [comment]
Thanks a lot Philipp,

it is well possible, that our firewall or other parts of the infrastructure is responsible for this behaviour.
The solution to load updates via manual donwloads is not too convinient but that doesn't matter :-)

Possibly I  will do that, if I can download the updates at all .....

Have a nice day! 
kind reagrds
Klaus

**Comment by KES48** [comment]
I think we can close this issue.
